apiVersion: apps/v1
kind: Deployment
metadata:
  prometheus.io/port: "8000"
  prometheus.io/path: "/metrics"
  prometheus.io/scrape: "true"
  name: payment-deployment
  labels:
    app: payment
  namespace: payment-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: mekniwassime/devops_project:payment-a14c4e34ed61d898450dd61c4e55cca71273929f
        ports:
        - containerPort: 80