apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  labels:
    app: payment
  namespace: payment-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      annotations:
        prometheus.io/port: "9000"
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: "true"
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: mekniwassime/devops_project:payment-06d331c79f99bd5d168f7bc610a5b16c5ac4fa0f
      - name: sidecar
        image: mekniwassime/devops_project:sidecarproxy-2c2a20f02f49da3ef590dbffafe7d5b56d3f0312
        env:
        - name: PORT
          value: "3000"
        - name: TARGET_PORT
          value: "8000"
        - name: UPSTREAM_HOST
          value: "localhost"