apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: payment-ingress
  namespace: payment-ns
spec:
  ingressClassName: nginx
  rules:
    - host: www..devops-project.com
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: payment-svc
                port:
                  number: 80
            path: /payment/