apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: payment-ns
  labels:
    service: mongo
spec:
  ports:
    - name: "mongo-port"
      port: 27017
      targetPort: 27017
  selector:
    service: mongo
status:
  loadBalancer: {}
