apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mongo
  template:
    metadata:
      labels:
        service: mongo
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_DATABASE
              value: bookstore
          image: mongo:4.4
          name: mongo
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db/
              name: mongo-claim0
            - mountPath: /docker-entrypoint-initdb.d/init-mongo.js
              name: mongo-claim1
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: mongo-claim0
          persistentVolumeClaim:
            claimName: mongo-claim0
        - name: mongo-claim1
          persistentVolumeClaim:
            claimName: mongo-claim1
            readOnly: true

