apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-claim1
spec:
  storageClassName: managed
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 200Mi
status: {}


