apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-claim0
  namespace: payment-ns
spec:
  storageClassName: managed
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
