apiVersion: v1
data:
  kustomize.buildOptions: --enable-helm
  application.instanceLabelKey: argocd.argoproj.io/instance
  exec.enabled: 'false'
  server.rbac.log.enforce.enable: 'false'
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: argocd
    meta.helm.sh/release-namespace: argocd
  creationTimestamp: '2023-01-17T08:14:16Z'
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
    helm.sh/chart: argo-cd-4.9.7
  name: argocd-cm
  namespace: argocd
  resourceVersion: '2459'
  uid: 0b04f01d-db84-4504-a9b1-a2023608d6d5
