name: Pants Pipeline
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: init pants
        run: |
          ls pants -l
          ./pants count-loc '**'
      - name: Print pants goals
        run: ./pants help goals
      - name: Setup shared_app package
        run: "./pants setup.py ::"