name: Devops Pipeline
on: [workflow_dispatch]

jobs:
  BuildServices:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ['admin', 'payment', 'product']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1
      - name: Build and push services to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.service }}/
          file: ${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/devops_project:${{matrix.service}}-${{ github.sha }},${{ secrets.DOCKER_HUB_USERNAME }}/devops_project:${{matrix.service}}-latest
      - name: Build and push sidecar proxy to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: sideproxy/
          file: sideproxy/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/devops_project:sidecarproxy-${{ github.sha }},${{ secrets.DOCKER_HUB_USERNAME }}/devops_project:sidecarproxy-latest
  BuildSidecar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1
      - name: Build and push sidecar proxy to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: sideproxy/
          file: sideproxy/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/devops_project:sidecarproxy-${{ github.sha }},${{ secrets.DOCKER_HUB_USERNAME }}/devops_project:sidecarproxy-latest
